-- Deprecated: multi-tenant `brands` / `brand_id` onboarding was removed.
-- Use the standard schema from `supabase/migrations/` (including
-- `20260417100000_revert_white_label_brands.sql` if you previously applied white-label).
-- Seed content directly in `products`, `categories`, `site_content`, `homepage_sections`,
-- `brand_settings`, and NFC tables as needed for a single deployment.
